version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=winehouse
    volumes:
      - winehouse_pg_data:/bitnami/postgresql
      - ./src/database/script.sql:/docker-entrypoint-initdb.d/script.sql:ro  

volumes:
  winehouse_pg_data: