version : '3.1'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports: 
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - winehouse_pg_data:/bitnami/postgresql
      - ../documentation/database/fisico.sql:/docker-entrypoint-initdb.d/init.sql:ro  

volumes:
  winehouse_pg_data: